### PR TITLE
Start with tini to avoid zombie processes

### PR DESCRIPTION
**Pull request by sukso96100**

### CODE REVIEW

**Comment by kenshaw** [comment]
Is there any reason you're submitting this? I haven't had issues with Zombie processes at all. I am very aware of `tini`, and have used it previously. However, `headless-shell` respects control signals and works well under Docker. Can you give a specific use case where a crashed `headless-shell` instance was causing child zombies to remain running in the container?

**Comment by sukso96100** [comment]
Hi, I've been used this image as base to tun go program that uses chromedp. 
After started running my program as a container on ECS, I found some problems that CPU utilization and memory usage keep increases even with the small network traffics.
스크린샷 2019-09-09 오후 6 18 51

I tried many ways to solve this problem such as analyzing escapes, checked if context cancel function is not called and tried to share single context among the program.

My colleague ran the program on both macOS host and inside docker container and monitored its processes. We found that headless-shell processes are managed well on macOS but not on the container.
스크린샷 2019-09-09 오후 7 54 07
스크린샷 2019-09-09 오후 7 56 41

[So we placed `dumb-init` on `ENTRYPOINT` of `Dockerfile` and solved the problem.](https://github.com/s-owl/skhus-backend/blob/6d7f0998c29520fca7c8170f6b15cabfcb4945a1/Dockerfile)

스크린샷 2019-09-10 오후 4 11 58
스크린샷 2019-09-11 오전 8 25 45

After that, i found other chrome docker images like [`browserless/chrome`](https://github.com/browserless/chrome/blob/master/Dockerfile) also uses `dumb-init` or `tini` for similar reason.

So i opened this PR but added `tini` because i thought it would work better on docker since it's shipped docker

**Comment by kenshaw** [comment]
How are you launching `headless-shell` from `chromedp`? The way we do this with my company, is on a new session, we launch a new pod on K8s. Are you reusing your `headless-shell` instances? K8s/Docker/whatever container orchestration you're using should reap the processes when it dies. I understand that may not be the way you're using `chromedp` + this image, but I'm just curious as to if this is a real problem. May I suggest instead to build your own image using `FROM chromedp/headless-shell` and use `tini` on that image?

**Comment by sukso96100** [comment]
If `headless-shell` doesn't causes zombies when running as a seperate container. I'll open another PR instead add a section about about using as base image on README.

**Comment by sukso96100** [comment]
@kenshaw 
My image just uses headless-shell as base by using `FROM chromedp/headless-shell`
https://github.com/s-owl/skhus-backend/blob/6d7f0998c29520fca7c8170f6b15cabfcb4945a1/Dockerfile

I usually create a context with `NewExecAllocator()` and launch multiple tabs from that context using `NewContext()`

https://github.com/s-owl/skhus-backend/blob/master/browser/browser.go

**Comment by sukso96100** [comment]
Thank you @kenshaw I will now just close this PR and open another PR that adds a section about using `headless-shell` as base image

**Comment by kenshaw** [comment]
I do appreciate the contribution! It's a bit of a philosophy thing, but I'd like to keep the image that this repo produces to the absolute, bare essential. I can understand how `tini` would be useful in some deployment/usage scenarios, but in my opinion, someone using this could easily build their own image with this as the `FROM ...` entry, and change the relevant sections if they need it.

**Pull request closed without merging**
