### PR TITLE
Dockerfile: Upgrade to Debian bookworm

### PR DESCRIPTION
**Pull request by mrueg**
Updates baseimage to bookworm, which was released in June 2023.

### CODE REVIEW

**Comment by mrueg** [comment]
@ZekeLu can you help out on this if you have a couple of spare cycles?

**Comment by ZekeLu** [comment]
@mrueg Thank you for the contribution and sorry for the late reply!

I have tried this pull request by copying the artifacts from the current `chromedp/headless-shell` images. See the `Dockerfile` below:

```Dockerfile
ARG VERSION

FROM chromedp/headless-shell:$VERSION AS original

FROM debian:bookworm-slim
RUN \
    apt-get update -y \
    && apt-get install --no-install-recommends -y libnspr4 libnss3 libexpat1 libfontconfig1 libuuid1 \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY --from=original \
    /headless-shell/headless-shell \
    /headless-shell/.stamp \
    /headless-shell/libEGL.so \
    /headless-shell/libGLESv2.so \
    /headless-shell/libvk_swiftshader.so \
    /headless-shell/libvulkan.so.1 \
    /headless-shell/vk_swiftshader_icd.json \
    /headless-shell/

EXPOSE 9222
ENV LANG en-US.UTF-8
ENV PATH /headless-shell:$PATH
ENTRYPOINT [ "/headless-shell/headless-shell", "--no-sandbox", "--use-gl=angle", "--use-angle=swiftshader", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
```

I have build new images from the following images:

- `chromedp/headless-shell:114.0.5735.199`
- `chromedp/headless-shell:115.0.5790.56`
- `chromedp/headless-shell:116.0.5845.14`

All of them passed the tests in the `chromedp` project (using https://github.com/chromedp/chromedp/blob/master/contrib/docker-test.sh).

So I think it's OK to merge this pull request.

@kenshaw Please take a look. BTW, `chromedp/headless-shell:latest` points to `chromedp/headless-shell:114.0.5735.199`, which was built 3 months ago. I'm afraid that the builder is broken again.

**Review by ZekeLu — APPROVED** [review]

**Comment by augustinaviciusR** [comment]
@kenshaw can this please be reviewed. I have been waiting for this change several months.

**Comment by ZekeLu** [comment]
@augustinaviciusR It seems that the build server is broken. I guess it's broken because `chromium` changed the build configuration too much recently. I'm afraid that it's not easy to fix. But kenshaw@ is too busy to take a look into it.

A workaround is to build your own image by copying the files from `chromedp/headless-shell`. See the Dockerfile in https://github.com/chromedp/docker-headless-shell/pull/22#issuecomment-1714940202 above.

**Comment by augustinaviciusR** [comment]
@ZekeLu thank you for quick response, I will follow instructions on workaround you provided.

**Comment by mrueg** [comment]
@kenshaw @ZekeLu any updates on this one? It would be nice to get an update version. The last tag https://hub.docker.com/r/chromedp/headless-shell/tags is 7 months old.

I don't know specifics about the build time of headless-shell, maybe this can be migrated to be built on github actions?

**Comment by jing-nmg** [comment]
DockerHub Need to update to the latest version. TKS

**Comment by kenshaw** [comment]
I have fixed the build infrastructure, and have added multi arch builds as well as updated to the latest Debian base image. Should be pushed to the Docker hub shortly.

**Pull request closed without merging**
